import os
import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def plot_reconstruction_dashboard(original, reconstructed, latent, epoch, save_path):
    """
    4-panel diagnostic dashboard to monitor Phase 1 (Representation Learning).
    
    1. Grid Reconstruction (Original vs Predicted)
    2. Error Heatmap (Spatial failing)
    3. Color Histogram (Palette matching)
    4. Latent Spectrum (Anti-collapse check)
    """
    original = original.cpu().numpy()
    reconstructed = reconstructed.cpu().numpy()
    latent = latent.cpu().detach().numpy()
    
    if latent.ndim == 1:
        latent = latent[np.newaxis, :]
    
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle(f"Phase 1 Diagnostic Dashboard - Epoch {epoch}", fontsize=16)

    # Panel 1: Reconstruction
    combined = np.hstack([original, reconstructed])
    axes[0, 0].imshow(combined, cmap='tab10', vmin=0, vmax=9)
    axes[0, 0].set_title("Original Grid (Left) vs. Reconstructed (Right)")
    axes[0, 0].axis('off')

    # Panel 2: Error Heatmap
    error = np.abs(original - reconstructed)
    sns.heatmap(error, ax=axes[0, 1], cmap="YlOrRd", cbar=True)
    axes[0, 1].set_title("Pixel-wise Error Heatmap")

    # Panel 3: Color Histogram Comparison
    target_counts = np.bincount(np.clip(np.round(original.flatten()), 0, 9).astype(int), minlength=10) / original.size
    recon_counts = np.bincount(np.clip(np.round(reconstructed.flatten()), 0, 9).astype(int), minlength=10) / reconstructed.size
    
    x = np.arange(10)
    axes[1, 0].bar(x - 0.2, target_counts, width=0.4, label='True', color='blue', alpha=0.6)
    axes[1, 0].bar(x + 0.2, recon_counts, width=0.4, label='Recon', color='red', alpha=0.6)
    axes[1, 0].set_xticks(x)
    axes[1, 0].set_title("Color Distribution Mapping")
    axes[1, 0].legend()

    # Panel 4: Latent Spectrum (Anti-collapse check)
    # std deviation across the latent dimensions
    latent_std = np.std(latent, axis=0) # [latent_dim]
    axes[1, 1].bar(range(len(latent_std)), latent_std, color='purple', alpha=0.7)
    axes[1, 1].set_title(f"Latent Spectrum (Mean Std: {latent_std.mean():.4f})")
    axes[1, 1].set_xlabel("Latent Dimension (1-128)")
    axes[1, 1].set_ylabel("Std Dev")

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.savefig(save_path)
    plt.close(fig)
    return save_path

def plot_world_model_predictions(orig_grid, true_next_grid, predicted_next_grid, action_text, epoch, save_path):
    """
    3-panel diagnostic dashboard for the World Model.
    Visualizes Input Grid -> [Action] -> Predicted Grid vs True Grid
    """
    import matplotlib.pyplot as plt
    import numpy as np

    # Ensure numpy arrays
    if hasattr(orig_grid, 'cpu'): orig_grid = orig_grid.cpu().numpy()
    if hasattr(true_next_grid, 'cpu'): true_next_grid = true_next_grid.cpu().numpy()
    if hasattr(predicted_next_grid, 'cpu'): predicted_next_grid = predicted_next_grid.cpu().numpy()

    # Squeeze out single dimensions
    orig_grid = np.squeeze(orig_grid)
    true_next_grid = np.squeeze(true_next_grid)
    predicted_next_grid = np.squeeze(predicted_next_grid)

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.suptitle(f"Phase 2 Diagnostic: World Model Predictions - Epoch {epoch}", fontsize=16)

    # Panel 1: Original State
    axes[0].imshow(orig_grid, cmap='tab10', vmin=0, vmax=9)
    axes[0].set_title(f"State $T$\nAction taken: {action_text}", fontsize=12)
    axes[0].axis('off')

    # Panel 2: Predicted Next State (Decoded from Latent)
    axes[1].imshow(predicted_next_grid, cmap='tab10', vmin=0, vmax=9)
    axes[1].set_title(f"Predicted State $T+1$\n(Model Hallucination)", fontsize=12)
    axes[1].axis('off')

    # Panel 3: True Next State
    axes[2].imshow(true_next_grid, cmap='tab10', vmin=0, vmax=9)
    axes[2].set_title(f"Ground Truth State $T+1$\n(Actual Physics)", fontsize=12)
    axes[2].axis('off')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    
    # Save safely
    import os
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    plt.savefig(save_path)
    plt.close(fig)
    return save_path

def plot_slot_masks(alphas, epoch, save_path):
    """
    Visualizes the raw alpha masks dynamically generated by the Slot Attention Decoder.
    """
    import os
    import numpy as np
    import matplotlib.pyplot as plt

    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    
    # alphas: [B, num_slots, 1, H, W]
    # We will visualize the first item in the batch
    if hasattr(alphas, 'cpu'): alphas = alphas.cpu().detach().numpy()
    
    alphas_b0 = alphas[0] # [num_slots, 1, H, W]
    num_slots = alphas_b0.shape[0]
    
    # Calculate grid size (e.g. 16 slots -> 4x4)
    grid_size = int(np.ceil(np.sqrt(num_slots)))
    
    fig, axes = plt.subplots(grid_size, grid_size, figsize=(12, 12))
    fig.suptitle(f"Slot Attention Alpha Assignments - Epoch {epoch}", fontsize=18)
    
    axes = axes.flatten()
    for i in range(len(axes)):
        if i < num_slots:
            mask = np.squeeze(alphas_b0[i]) # [H, W]
            axes[i].imshow(mask, cmap='magma', vmin=0, vmax=1)
            axes[i].set_title(f"Slot {i+1}", fontsize=10)
        axes[i].axis('off')
        
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.savefig(save_path, dpi=150)
    plt.close(fig)
    return save_path
