import os
import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def plot_reconstruction_dashboard(original, reconstructed, latent, epoch, save_path):
    """
    4-panel diagnostic dashboard to monitor Phase 1 (Representation Learning).
    
    1. Grid Reconstruction (Original vs Predicted)
    2. Error Heatmap (Spatial failing)
    3. Color Histogram (Palette matching)
    4. Latent Spectrum (Anti-collapse check)
    """
    original = original.cpu().detach().numpy()
    reconstructed = reconstructed.cpu().detach().numpy()
    latent = latent.cpu().detach().numpy()
    
    if latent.ndim == 1:
        latent = latent[np.newaxis, :]
        
    # Auto-detect if reconstructed contains 10 class logits [10, H, W] instead of 1 channel
    if reconstructed.ndim == 3 and reconstructed.shape[0] > 1:
        reconstructed = np.argmax(reconstructed, axis=0)
        
    original = np.squeeze(original)
    reconstructed = np.squeeze(reconstructed)
    
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle(f"Phase 1 Diagnostic Dashboard - Epoch {epoch}", fontsize=16)

    # Panel 1: Reconstruction
    combined = np.hstack([original, reconstructed])
    axes[0, 0].imshow(combined, cmap='tab10', vmin=0, vmax=9)
    axes[0, 0].set_title("Original Grid (Left) vs. Reconstructed (Right)")
    axes[0, 0].axis('off')

    # Panel 2: Error Heatmap
    error = np.abs(original - reconstructed)
    sns.heatmap(error, ax=axes[0, 1], cmap="YlOrRd", cbar=True)
    axes[0, 1].set_title("Pixel-wise Error Heatmap")

    # Panel 3: Color Histogram Comparison
    target_counts = np.bincount(np.clip(np.round(original.flatten()), 0, 9).astype(int), minlength=10) / original.size
    recon_counts = np.bincount(np.clip(np.round(reconstructed.flatten()), 0, 9).astype(int), minlength=10) / reconstructed.size
    
    x = np.arange(10)
    axes[1, 0].bar(x - 0.2, target_counts, width=0.4, label='True', color='blue', alpha=0.6)
    axes[1, 0].bar(x + 0.2, recon_counts, width=0.4, label='Recon', color='red', alpha=0.6)
    axes[1, 0].set_xticks(x)
    axes[1, 0].set_title("Color Distribution Mapping")
    axes[1, 0].legend()

    # Panel 4: Latent Spectrum (Anti-collapse check)
    # std deviation across the latent dimensions
    latent_std = np.std(latent, axis=0) # [latent_dim]
    axes[1, 1].bar(range(len(latent_std)), latent_std, color='purple', alpha=0.7)
    axes[1, 1].set_title(f"Latent Spectrum (Mean Std: {latent_std.mean():.4f})")
    axes[1, 1].set_xlabel("Latent Dimension (1-128)")
    axes[1, 1].set_ylabel("Std Dev")

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.savefig(save_path)
    plt.close(fig)
    return save_path

def plot_world_model_predictions(orig_grid, true_next_grid, predicted_next_grid, action_text, epoch, save_path):
    """
    3-panel diagnostic dashboard for the World Model.
    Visualizes Input Grid -> [Action] -> Predicted Grid vs True Grid
    """
    import matplotlib.pyplot as plt
    import numpy as np

    # Ensure numpy arrays
    if hasattr(orig_grid, 'cpu'): orig_grid = orig_grid.cpu().numpy()
    if hasattr(true_next_grid, 'cpu'): true_next_grid = true_next_grid.cpu().numpy()
    if hasattr(predicted_next_grid, 'cpu'): predicted_next_grid = predicted_next_grid.cpu().numpy()

    # Squeeze out single dimensions
    orig_grid = np.squeeze(orig_grid)
    true_next_grid = np.squeeze(true_next_grid)
    predicted_next_grid = np.squeeze(predicted_next_grid)

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.suptitle(f"Phase 2 Diagnostic: World Model Predictions - Epoch {epoch}", fontsize=16)

    # Panel 1: Original State
    axes[0].imshow(orig_grid, cmap='tab10', vmin=0, vmax=9)
    axes[0].set_title(f"State $T$\nAction taken: {action_text}", fontsize=12)
    axes[0].axis('off')

    # Panel 2: Predicted Next State (Decoded from Latent)
    axes[1].imshow(predicted_next_grid, cmap='tab10', vmin=0, vmax=9)
    axes[1].set_title(f"Predicted State $T+1$\n(Model Hallucination)", fontsize=12)
    axes[1].axis('off')

    # Panel 3: True Next State
    axes[2].imshow(true_next_grid, cmap='tab10', vmin=0, vmax=9)
    axes[2].set_title(f"Ground Truth State $T+1$\n(Actual Physics)", fontsize=12)
    axes[2].axis('off')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    
    # Save safely
    import os
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    plt.savefig(save_path)
    plt.close(fig)
    return save_path

def plot_slot_masks(alphas, epoch, save_path):
    """
    Visualizes the raw alpha masks dynamically generated by the Slot Attention Decoder.
    """
    import os
    import numpy as np
    import matplotlib.pyplot as plt

    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    
    # alphas: [B, num_slots, 1, H, W]
    # We will visualize the first item in the batch
    if hasattr(alphas, 'cpu'): alphas = alphas.cpu().detach().numpy()
    
    alphas_b0 = alphas[0] # [num_slots, 1, H, W]
    num_slots = alphas_b0.shape[0]
    
    # Calculate grid size (e.g. 16 slots -> 4x4)
    grid_size = int(np.ceil(np.sqrt(num_slots)))
    
    fig, axes = plt.subplots(grid_size, grid_size, figsize=(12, 12))
    fig.suptitle(f"Slot Attention Alpha Assignments - Epoch {epoch}", fontsize=18)
    
    axes = axes.flatten()
    for i in range(len(axes)):
        if i < num_slots:
            mask = np.squeeze(alphas_b0[i]) # [H, W]
            axes[i].imshow(mask, cmap='magma', vmin=0, vmax=1)
            axes[i].set_title(f"Slot {i+1}", fontsize=10)
        axes[i].axis('off')
        
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.savefig(save_path, dpi=150)
    plt.close(fig)
    return save_path

# ── ARC COLOR MAP ────────────────────────────────────────────────────────────
ARC_COLORS = ["#000000", "#0074D9", "#FF4136", "#2ECC40", "#FFDC00", 
              "#AAAAAA", "#F012BE", "#FF851B", "#7FDBFF", "#870C25"]
from matplotlib.colors import ListedColormap
ARC_CMAP = ListedColormap(ARC_COLORS)

@torch.no_grad()
def plot_phase0_factorization(model, epoch, save_path, device='cpu'):
    """
    Diagnostic plot to verify that Shape and Color are truly factorized in Phase 0.
    Generates a matrix of 5 shapes across 5 colors.
    """
    model.eval()
    vq = model.vq
    
    # 1. Get 5 Shape codes and 5 Color codes (avoiding BG codes 0-2)
    s_indices = [3, 10, 20, 50, 100]
    c_indices = [3, 7, 12, 18, 25]
    
    fig, axes = plt.subplots(len(s_indices), len(c_indices), figsize=(12, 12))
    fig.suptitle(f"Phase 0 Factorization Sweep (Shape vs Color) - Epoch {epoch}", fontsize=16)
    
    for i, s_idx in enumerate(s_indices):
        for j, c_idx in enumerate(c_indices):
            # Combine manually: [1, 1, D]
            s_emb = vq.embedding_shape.weight[s_idx]
            c_emb = vq.embedding_color.weight[c_idx]
            z_q = (s_emb + c_emb).unsqueeze(0).unsqueeze(0)
            
            # Pad with zero pose
            pose_dim = getattr(model.decoder, 'pose_dim', 0)
            if pose_dim > 0:
                pose_zeros = torch.zeros(1, 1, pose_dim, device=z_q.device)
                z_full = torch.cat([z_q, pose_zeros], dim=-1)
            else:
                z_full = z_q
                
            out = model.decoder({'latent': z_full})['reconstructed_logits']
            img = out.argmax(dim=1).squeeze().cpu().numpy()
            
            ax = axes[i, j]
            ax.imshow(img, cmap=ARC_CMAP, vmin=0, vmax=9)
            if i == 0: ax.set_title(f"Color {c_idx}")
            if j == 0: ax.set_ylabel(f"Shape {s_idx}")
            ax.set_xticks([]); ax.set_yticks([])
            
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.savefig(save_path, dpi=120)
    plt.close(fig)

@torch.no_grad()
def plot_phase1_object_summary(states, outputs, slot_enc, epoch, save_path):
    """
    Comprehensive Object-Centric Validation for Phase 1.
    Rows: Each Slot (Mask, Shape Reconstruction, Color Distribution)
    Header: Original vs Global Reconstruction vs Error Heatmap
    """
    import torch.nn.functional as F
    
    # states: [B, 1, 30, 30], recon: [B, 10, 30, 30], alphas: [B, K, 1, 30, 30]
    orig  = states[0, 0].cpu().numpy()
    recon = outputs['reconstruction'][0].argmax(dim=0).cpu().numpy()
    alphas = outputs['alphas'][0].cpu().numpy() # [K, 1, 30, 30]
    slots_latent = outputs.get('latent', None)  # [B, K, D]
    
    K = alphas.shape[0]
    num_vis_slots = min(K, 8) # Limit to first 8 slots for clarity
    
    fig = plt.figure(figsize=(16, 4 + 2 * num_vis_slots))
    gs = fig.add_gridspec(num_vis_slots + 1, 4)
    fig.suptitle(f"Phase 1: Object-Centric Diagnostic - Epoch {epoch}", fontsize=20)

    # --- Header Row ---
    ax_orig = fig.add_subplot(gs[0, 0])
    ax_orig.imshow(orig, cmap=ARC_CMAP, vmin=0, vmax=9)
    ax_orig.set_title("Original Input")
    
    ax_recon = fig.add_subplot(gs[0, 1])
    ax_recon.imshow(recon, cmap=ARC_CMAP, vmin=0, vmax=9)
    ax_recon.set_title("Full Reconstruction")
    
    ax_err = fig.add_subplot(gs[0, 2])
    error = (orig != recon).astype(float)
    sns.heatmap(error, ax=ax_err, cmap="Reds", cbar=False)
    ax_err.set_title("Error Heatmap")

    # --- Slot-by-Slot Rows ---
    for k in range(num_vis_slots):
        # 1. Alpha Mask
        ax_mask = fig.add_subplot(gs[k+1, 0])
        ax_mask.imshow(alphas[k, 0], cmap='magma', vmin=0, vmax=1)
        ax_mask.set_ylabel(f"Slot {k}", fontsize=12, fontweight='bold')
        if k == 0: ax_mask.set_title("Alpha Mask")
        
        # 2. Individual Slot Reconstruction (Primitive)
        # We can extract the color predicted for this slot specifically
        # colors: [B, K, 10, H, W]
        slot_colors = outputs['colors'][0, k].argmax(dim=0).cpu().numpy()
        ax_prim = fig.add_subplot(gs[k+1, 1])
        # Mask the color by its own alpha to see the "object" clearly
        ax_prim.imshow(slot_colors, cmap=ARC_CMAP, vmin=0, vmax=9, alpha=0.8)
        if k == 0: ax_prim.set_title("Slot Primitive")
        
        # 3. Color distribution for this slot
        ax_hist = fig.add_subplot(gs[k+1, 2])
        # Get logits for this slot's pixels
        logits = outputs['colors'][0, k].permute(1, 2, 0).cpu().numpy() # [H, W, 10]
        # Weight by alpha
        mask_flat = alphas[k, 0].flatten()
        logits_flat = logits.reshape(-1, 10)
        weighted_probs = (np.exp(logits_flat) / np.sum(np.exp(logits_flat), axis=1, keepdims=True)) * mask_flat[:, None]
        dist = weighted_probs.mean(axis=0)
        ax_hist.bar(range(10), dist, color=ARC_COLORS)
        ax_hist.set_ylim(0, 1.1)
        if k == 0: ax_hist.set_title("Color Distribution")

        # 4. Nearest Code IDs (Symbolic Mapping)
        if slots_latent is not None:
            ax_text = fig.add_subplot(gs[k+1, 3])
            ax_text.axis('off')
            
            # Find nearest VQ codes for this slot (Shape/Color)
            # Need access to the codebook weights
            vq = slot_enc.codebook_shape # [1024, D_s]
            z_s = slots_latent[0, k, :vq.shape[1]]
            dist_s = torch.cdist(z_s.unsqueeze(0), vq).argmin().item()
            
            info = f"Symbolic ID:\nShape: #{dist_s}\nColor: Variable"
            ax_text.text(0.1, 0.5, info, fontsize=12, family='monospace')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.savefig(save_path, dpi=120)
    plt.close(fig)
